interval = 600

[[servers]]
name = "staing api"
url = "https://api.staging.example.com/status"
method = "GET"
timeout = 10
status_code = 200
slack_webhook = "https://hooks.slack.com/services/***/***"
slack_channel_alert = "staging-alert"
slack_channel_log = "staging-log"

[[servers]]
name = "production api"
url = "https://api.example.com/status"
method = "GET"
timeout = 20
status_code = 200
slack_webhook = "https://hooks.slack.com/services/***/***"
slack_channel_alert = "production-alert"
slack_channel_log = "production-log"

[[servers]]
name = "post api"
url = "https://api.example.com/post"
method = "POST"
timeout = 20
status_code = 201
slack_webhook = "https://hooks.slack.com/services/***/***"
slack_channel_alert = "post-alert"
slack_channel_log = "post-log"
